CREATE TABLE local_pokemon (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    poke_api_id    INTEGER       NOT NULL,
    name           VARCHAR(50)   NOT NULL,
    sprite_url     VARCHAR(500),
    category       VARCHAR(50),
    weight_kg      NUMERIC(5, 1) NOT NULL,
    localized_name VARCHAR(100),
    region         VARCHAR(100),
    CONSTRAINT uk_local_pokemon_poke_api_id UNIQUE (poke_api_id)
);

CREATE TABLE local_pokemon_abilities (
    local_pokemon_id BIGINT      NOT NULL,
    position         INTEGER     NOT NULL,
    ability          VARCHAR(50) NOT NULL,
    CONSTRAINT pk_local_pokemon_abilities PRIMARY KEY (local_pokemon_id, position),
    CONSTRAINT fk_local_pokemon_abilities_local_pokemon FOREIGN KEY (local_pokemon_id) REFERENCES local_pokemon (id)
);

CREATE TABLE local_pokemon_internal_tags (
    local_pokemon_id BIGINT      NOT NULL,
    position         INTEGER     NOT NULL,
    tag              VARCHAR(30) NOT NULL,
    CONSTRAINT pk_local_pokemon_internal_tags PRIMARY KEY (local_pokemon_id, position),
    CONSTRAINT fk_local_pokemon_internal_tags_local_pokemon FOREIGN KEY (local_pokemon_id) REFERENCES local_pokemon (id)
);
