CREATE TABLE tasks (
    id          BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(120)                NOT NULL,
    description VARCHAR(2000),
    status      VARCHAR(11)                 NOT NULL,
    due_date    DATE                        NOT NULL,
    owner_id    BIGINT                      NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tasks_owner FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX idx_tasks_owner_due_date ON tasks (owner_id, due_date, id);
